# Generated by Django 5.2.1 on 2025-10-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
